/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pauasms;

import classes.ActivityUpdater;
import classes.EmailSender;
import com.formdev.flatlaf.FlatLightLaf;
//import java.awt.List;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
//import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.Timestamp;
import java.util.List;
import java.util.ArrayList;


/**
 *
 * @author Nkon1
 */
public class Dos extends javax.swing.JFrame {

    /**
     * Creates new form Dos
     */
    public Dos() {
        initComponents();
        try{
            jLabel2.setText(login.jTextField1.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error getting user name, please sign in: " + e.getMessage());
            System.out.println("Error getting user name, please sign in: " + e.getMessage());
        }
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/logo3.png"));
        setIconImage(icon.getImage());
        
        //Setting Frame Title
        this.setTitle("Director of Services / Head of IT");
        
        ActivityUpdater Dos = new ActivityUpdater();
        
        ScheduledExecutorService scheduler1 = Executors.newSingleThreadScheduledExecutor();
        scheduler1.scheduleAtFixedRate(() -> {
            SwingUtilities.invokeLater(() -> {
                Dos.loadUserActivities(jTable1); // Your JTable
            });
        }, 0, 2500, TimeUnit.MILLISECONDS);
 
        ScheduledExecutorService scheduler2 = Executors.newSingleThreadScheduledExecutor();
        scheduler2.scheduleAtFixedRate(() -> {
            SwingUtilities.invokeLater(() -> {
                manageAttendance(jTable2); // Your JTable
            });
        }, 0, 2500, TimeUnit.MILLISECONDS);
        
        ScheduledExecutorService scheduler3 = Executors.newSingleThreadScheduledExecutor();
        scheduler3.scheduleAtFixedRate(() -> {
            SwingUtilities.invokeLater(() -> {
                viewRoster(jTable3); // Your JTable
            });
        }, 0, 2500, TimeUnit.MILLISECONDS);  
        
        ScheduledExecutorService scheduler4 = Executors.newSingleThreadScheduledExecutor();
        scheduler4.scheduleAtFixedRate(() -> {
            SwingUtilities.invokeLater(() -> {
                Dos.manageUsers(jTable4); // Your JTable
            });
        }, 0, 2500, TimeUnit.MILLISECONDS);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(46, 56, 106));

        jLabel1.setFont(new java.awt.Font("Space Mono", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome,");

        jLabel2.setFont(new java.awt.Font("Space Mono", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");

        jTabbedPane1.setBackground(new java.awt.Color(46, 56, 106));

        jPanel2.setBackground(new java.awt.Color(46, 56, 106));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User Activities", jPanel2);

        jPanel4.setBackground(new java.awt.Color(46, 56, 106));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Filter By:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Date:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Staff ID:");

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(102, 0, 0));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(46, 56, 106));
        jButton8.setText("Filter");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Unit:");

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unit", "Security", "Horticulture", "Facility", "Cafeteria", "Maintenance" }));

        jButton1.setBackground(new java.awt.Color(46, 56, 106));
        jButton1.setText("Download Roster");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
            .addComponent(jScrollPane5)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton8))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Staff Rosters", jPanel4);

        jPanel5.setBackground(new java.awt.Color(46, 56, 106));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 356, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Staff Details", jPanel5);

        jPanel6.setBackground(new java.awt.Color(46, 56, 106));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Old Password:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("New Password:");

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setForeground(new java.awt.Color(102, 0, 0));

        jPasswordField2.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setForeground(new java.awt.Color(102, 0, 0));

        jButton10.setBackground(new java.awt.Color(46, 56, 106));
        jButton10.setText("Reset Password");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButton10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPasswordField2))))
                .addGap(495, 495, 495))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton10)
                .addContainerGap(445, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reset Password", jPanel6);

        jPanel3.setBackground(new java.awt.Color(46, 56, 106));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setBackground(new java.awt.Color(46, 56, 106));
        jButton2.setText("Download Log");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Filter By:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Date: ");

        jDateChooser1.setBackground(new java.awt.Color(204, 204, 204));
        jDateChooser1.setForeground(new java.awt.Color(102, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Staff ID:");

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(102, 0, 0));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Unit:");

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setForeground(new java.awt.Color(46, 56, 106));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Unit", "Security", "Horticulture", "Facility", "Cafeteria", "Maintenance" }));

        jButton6.setBackground(new java.awt.Color(46, 56, 106));
        jButton6.setText("Clear Filter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(46, 56, 106));
        jButton7.setText("Filter");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(32, 32, 32))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6)
                        .addComponent(jButton7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Sign-in Logs", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    Date selectedDate = jDateChooser2.getDate();
    String staffIdText = jTextField2.getText().trim();
    String selectedUnit = jComboBox1.getSelectedItem() != null ? 
                        jComboBox1.getSelectedItem().toString() : "";

    if (selectedDate == null && staffIdText.isEmpty() && 
        (selectedUnit.isEmpty() || selectedUnit.equals("Unit"))) {
        JOptionPane.showMessageDialog(null, 
            "Please select at least one filter (Date, Staff ID, or Unit)", 
            "Filter Required", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
    model.setRowCount(0);
    model.setColumnIdentifiers(new String[]{
        "Shift ID", "Staff Name", "Shift Date", "Shift Time", "Staff Unit"
    });

    StringBuilder query = new StringBuilder("""
        SELECT s.id, s.staff_name, s.shift_date, 
               s.shift_start_time, s.shift_end_time, s.unit,
               ud.user_id
        FROM shifts s
        JOIN userdetails ud ON s.staff_name = ud.name
        WHERE 1=1
        """);

    if (selectedDate != null) {
        query.append(" AND DATE(s.shift_date) = ?");
    }
    if (!staffIdText.isEmpty()) {
        query.append(" AND ud.user_id = ?");
    }
    if (!selectedUnit.isEmpty() && !selectedUnit.equals("Unit")) {
        query.append(" AND s.unit = ?");
    }
    query.append(" ORDER BY s.shift_date, s.shift_start_time");

    try (Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/asms_schema", 
            "root", 
            "root..");
         PreparedStatement pst = conn.prepareStatement(query.toString())) {

        int paramIndex = 1;
        if (selectedDate != null) {
            pst.setDate(paramIndex++, new java.sql.Date(selectedDate.getTime()));
        }
        if (!staffIdText.isEmpty()) {
            try {
                pst.setInt(paramIndex++, Integer.parseInt(staffIdText));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, 
                    "Invalid Staff ID. Must be a number.", 
                    "Input Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if (!selectedUnit.isEmpty() && !selectedUnit.equals("Unit")) {
            pst.setString(paramIndex, selectedUnit);
        }

        ResultSet rs = pst.executeQuery();
        boolean hasResults = false;

        while (rs.next()) {
            hasResults = true;
            String startTime = rs.getTime("shift_start_time").toString().substring(0, 5);
            String endTime = rs.getTime("shift_end_time").toString().substring(0, 5);
            
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("staff_name"),
                rs.getDate("shift_date"),
                startTime + " - " + endTime,
                rs.getString("unit")
            });
        }

        if (!hasResults) {
            JOptionPane.showMessageDialog(null, 
                "No shifts found matching the criteria", 
                "No Results", 
                JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, 
            "Database Error: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }finally{
        jDateChooser2.setDate(null);  // Clear date selection
        jTextField2.setText(""); // Clear staff ID field
        jComboBox1.setSelectedItem("Unit");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ActivityUpdater.exportRosterToCSV(jFileChooser1, this);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ActivityUpdater.exportSignInLogToCSV(jFileChooser1, this);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public String Hash(String c)
    {
    try{
    MessageDigest msgDigest = MessageDigest.getInstance("MD5");
     msgDigest.update((new String(c)).getBytes("UTF8"));
     String passHash = new String(msgDigest.digest());
     return passHash;
     
     
    }
    
    catch (Exception ex)
    {
    return c;
    
    }
    }
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            String username = jLabel2.getText(); // Assuming you store the logged-in username here
            String oldPassword = new String(jPasswordField1.getPassword());
            String newPassword = new String(jPasswordField2.getPassword());

            if (oldPassword.isEmpty() || newPassword.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter both old and new passwords");
                return;
            }

            if (oldPassword.equals(newPassword)) {
                JOptionPane.showMessageDialog(this, "New password cannot be the same as old password");
                return;
            }

            String hashedOldPassword = Hash(oldPassword);
            String hashedNewPassword = Hash(newPassword);

            try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/asms_schema", "root", "root..")) {

            try (PreparedStatement ps = con.prepareStatement(
                "SELECT password, useremail FROM userdetails WHERE username = ?")) {
            ps.setString(1, username);

            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(this, "User not found");
                    return;
                }

                String storedPassword = rs.getString("password");
                if (!hashedOldPassword.equals(storedPassword)) {
                    JOptionPane.showMessageDialog(this, "Current password is incorrect");
                    return;
                }

                try (PreparedStatement updatePs = con.prepareStatement(
                    "UPDATE userdetails SET password = ? WHERE username = ?")) {
                updatePs.setString(1, hashedNewPassword);
                updatePs.setString(2, username);

                int updated = updatePs.executeUpdate();
                if (updated > 0) {
                    logPasswordChangeActivity(con, username);

                    String email = rs.getString("useremail");
                    sendPasswordChangeEmail(username, email, newPassword);

                    JOptionPane.showMessageDialog(this, "Password changed successfully");
                    clearPasswordFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Password update failed");
                }
            }
        }
        }
        }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error changing password: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        }

        private void clearPasswordFields() {
            jPasswordField1.setText("");
            jPasswordField2.setText("");
        }

        private void logPasswordChangeActivity(Connection con, String username) throws SQLException {
            try (PreparedStatement ps = con.prepareStatement(
                "INSERT INTO useractivities (username, activitytype, details) VALUES (?, ?, ?)")) {
            ps.setString(1, username);
            ps.setString(2, "Password Change");
            ps.setString(3, "User changed their own password");
            ps.executeUpdate();
        }
        }

        private void sendPasswordChangeEmail(String username, String receiver, String newPassword) {
            try {
                String subject = "Password Changed Notification";
                String body = "Hello " + username + ",\n\n" +
                "Your password was successfully changed.\n\n" +
                "For security reasons, we don't include your new password in this email.\n\n" +
                "If you didn't make this change, please contact IT immediately.\n\n" +
                "Best Regards,\n" +
                "The ASMS Team";

                EmailSender.send(receiver, subject, body);
            } catch (Exception e) {
                System.err.println("Failed to send email: " + e.getMessage());
            }

            // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

        
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    jDateChooser1.setDate(null);
    jTextField1.setText("");
    jComboBox2.setSelectedIndex(0); 
//    filterSignInLog(); // Refresh with no filters

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    Date selectedDate = jDateChooser1.getDate();
    String staffId = jTextField1.getText().trim();
    String unit = (String) jComboBox2.getSelectedItem();

    if ((selectedDate == null) && staffId.isEmpty() && 
        (unit == null || unit.equalsIgnoreCase("All") || unit.trim().isEmpty())) {
        JOptionPane.showMessageDialog(this, "Please select at least one filter", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/asms_schema",
            "root",
            "root..")) {

        DefaultTableModel model = (DefaultTableModel) jTable6.getModel();
        model.setRowCount(0);

        if (model.getColumnCount() == 0) {
            model.setColumnIdentifiers(new String[]{
                "User ID", "Name", "Sign in Time",
                "Sign out Time", "Sign in Status", "Sign out Status"
            });
        }

        StringBuilder queryBuilder = new StringBuilder("""
            SELECT sl.*, ud.user_id
            FROM signin_log sl
            JOIN userdetails ud ON sl.name = ud.name
            WHERE 1 = 1
        """);

        List<Object> parameters = new ArrayList<>();

        if (selectedDate != null) {
            queryBuilder.append(" AND DATE(sl.sign_in_time) = ?");
            parameters.add(new java.sql.Date(selectedDate.getTime()));
        }

        if (!staffId.isEmpty()) {
            try {
                int staffIdInt = Integer.parseInt(staffId);
                queryBuilder.append(" AND ud.user_id = ?");
                parameters.add(staffIdInt);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Staff ID must be numeric.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        if (unit != null && !unit.equalsIgnoreCase("All") && !unit.trim().isEmpty()) {
            queryBuilder.append(" AND ud.unit = ?");
            parameters.add(unit);
        }

        queryBuilder.append(" ORDER BY sl.sign_in_time DESC");

        try (PreparedStatement psa = con.prepareStatement(queryBuilder.toString())) {
            for (int i = 0; i < parameters.size(); i++) {
                psa.setObject(i + 1, parameters.get(i));
            }

            try (ResultSet rs = psa.executeQuery()) {
                boolean hasResults = false;

                while (rs.next()) {
                    hasResults = true;
                    model.addRow(new Object[]{
                        rs.getInt("user_id"),
                        rs.getString("name"),
                        formatDateTime(rs.getTimestamp("sign_in_time")),
                        formatDateTime(rs.getTimestamp("sign_out_time")),
                        rs.getString("sign_in_status"),
                        rs.getString("sign_out_status")
                    });
                }

                if (!hasResults) {
                    JOptionPane.showMessageDialog(this,
                            "No records found for the selected filters",
                            "Information",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Database error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Unexpected error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }

        // TODO add your handling code here:
        }

        private String formatDateTime(Timestamp timestamp) {
            if (timestamp == null) return "N/A";
            return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(timestamp);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    
        public void manageAttendance(JTable populerItemsTable) {
//        String username = jLabel2.getText();
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
        System.out.println("connected");

//        PreparedStatement ps= con.prepareStatement("select unit from userdetails where username=?");
//        ps.setString(1, username);
//        ResultSet rs=ps.executeQuery();
        
            DefaultTableModel model = (DefaultTableModel) populerItemsTable.getModel();
            model.setRowCount(0);

            String[] columnNames = {"User ID", "Name", "Sign in Time", "Sign out Time", "Sign in Status", "Sign out Status"};
            model.setColumnIdentifiers(columnNames);

            String query = """
                SELECT sl.*, ud.user_id 
                FROM signin_log sl
                JOIN userdetails ud ON sl.name = ud.name
                ORDER BY sl.sign_in_time DESC;
                """;
            

                
            PreparedStatement psa = con.prepareStatement(query);
            ResultSet rs1 = psa.executeQuery();
//            ResultSet rt =psa.executeQuery();

            while (rs1.next()) {
                model.addRow(new Object[]{
                    rs1.getInt("user_id"),
                    rs1.getString("name"),
                    rs1.getString("sign_in_time"),
                    rs1.getString("sign_out_time"),
                    rs1.getString("sign_in_status"),
                    rs1.getString("sign_out_status"),
                });
            }

        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
}
        
    public void viewRoster(JTable shiftsTable) {
//    String unit = null;

    DefaultTableModel model = (DefaultTableModel) shiftsTable.getModel();
    model.setRowCount(0);

    String[] columnNames = {"Shift ID", "Staff Name", "Shift Date", "Shift Time", "Staff Unit"};
    model.setColumnIdentifiers(columnNames);

    String query = """
        SELECT id, staff_name, shift_date, shift_start_time, shift_end_time, unit
        FROM shifts
        ORDER BY id ASC
        """;

    try (
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
        PreparedStatement pst = conn.prepareStatement(query);
    ) {
//        pst.setString(1, unit);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String startTime = rs.getTime("shift_start_time").toString().substring(0, 5);
            String endTime = rs.getTime("shift_end_time").toString().substring(0, 5);
            String shiftTime = startTime + "-" + endTime;

            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("staff_name"),
                rs.getDate("shift_date"),
                shiftTime,
                rs.getString("unit")
            });
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error loading shifts: " + e.getMessage());
    }
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    try {
        UIManager.setLookAndFeel(new FlatLightLaf());
    } catch (UnsupportedLookAndFeelException e) {
        e.printStackTrace();
    }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
