/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pauasms;

import classes.ActivityUpdater;
import classes.EmailSender;
import com.formdev.flatlaf.FlatLightLaf;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.SQLException;



/**
 *
 * @author Nkon1
 */
public class nonSupervisor extends javax.swing.JFrame {

    /**
     * Creates new form nonSupervisor
     */
    public nonSupervisor() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/logo3.png"));
        setIconImage(icon.getImage());
        
        //Setting Frame Title
        this.setTitle("Non-Supervising Staff");
        
        try{
            jLabel2.setText(login.jTextField1.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error getting username. Please Log In. Error: " + e.getMessage());
            System.out.println("Error getting username. Please Log In. Error: " + e.getMessage());
        }
        getProfile();
//        displayShift(jTable1);
        
        ActivityUpdater nonSup = new ActivityUpdater();
        
        ScheduledExecutorService scheduler5 = Executors.newSingleThreadScheduledExecutor();
        scheduler5.scheduleAtFixedRate(() -> {
            SwingUtilities.invokeLater(() -> {
            nonSup.viewOtherStaffShifts(jTable2, jLabel2.getText()); // Your JTable
            });
        }, 0, 10000, TimeUnit.MILLISECONDS);

        ScheduledExecutorService scheduler6 = Executors.newSingleThreadScheduledExecutor();
        scheduler6.scheduleAtFixedRate(() -> {
            SwingUtilities.invokeLater(() -> {
            displayShift(jTable1); // Your JTable
            });
        }, 0, 5000, TimeUnit.MILLISECONDS);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(46, 56, 106));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Welcome:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("_________");

        jTabbedPane1.setBackground(new java.awt.Color(46, 56, 106));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("DOB:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Phone Number:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Gender:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Unit:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Role:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("_________");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("_________");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("_________");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("_________");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("_________");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("_________");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("_________");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addContainerGap(902, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16))
                .addContainerGap(458, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Profile", jPanel2);

        jPanel3.setBackground(new java.awt.Color(46, 56, 106));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 377, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Shift Info", jPanel3);

        jPanel4.setBackground(new java.awt.Color(46, 56, 106));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setBackground(new java.awt.Color(46, 56, 106));
        jButton1.setText("Request Swap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 336, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Request Shift Swap", jPanel4);

        jPanel5.setBackground(new java.awt.Color(46, 56, 106));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Old Password:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("New Password:");

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setForeground(new java.awt.Color(102, 0, 0));

        jPasswordField2.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setForeground(new java.awt.Color(102, 0, 0));

        jButton10.setBackground(new java.awt.Color(46, 56, 106));
        jButton10.setText("Reset Password");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPasswordField2))))
                .addGap(495, 495, 495))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton10)
                .addContainerGap(466, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reset Password", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(77, 77, 77))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getNameFromUsername(String username) {
    try (
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
        PreparedStatement ps = conn.prepareStatement("SELECT name FROM userdetails WHERE username = ?");
    ) {
        ps.setString(1, username);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            return rs.getString("name");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return null;
}
    
    public int getMyLatestShiftId(String name) {
    try (
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
        PreparedStatement ps = conn.prepareStatement(
            "SELECT id FROM shifts WHERE staff_name = ? ORDER BY shift_date DESC LIMIT 1"
        );
    ) {
        ps.setString(1, name);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            return rs.getInt("id");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return -1;
}


    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int selectedRow = jTable2.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a shift to swap with.");
        return;
    }

    String requesterUsername = jLabel2.getText();
    String requesterName = getNameFromUsername(requesterUsername); 
    int targetShiftId = (int) jTable2.getValueAt(selectedRow, 0);
    String targetName = (String) jTable2.getValueAt(selectedRow, 1);

    
    int requesterShiftId = getMyLatestShiftId(requesterName); 

    try (
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
        PreparedStatement ps = conn.prepareStatement(
            "INSERT INTO shift_swaps (requester_name, target_name, requester_shift_id, target_shift_id) VALUES (?, ?, ?, ?)"
        );
    ) {
        ps.setString(1, requesterName);
        ps.setString(2, targetName);
        ps.setInt(3, requesterShiftId);
        ps.setInt(4, targetShiftId);

        int rows = ps.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Shift swap request sent!");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to send request.");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public String Hash(String c)
    {
    try{
    MessageDigest msgDigest = MessageDigest.getInstance("MD5");
     msgDigest.update((new String(c)).getBytes("UTF8"));
     String passHash = new String(msgDigest.digest());
     return passHash;
     
     
    }
    
    catch (Exception ex)
    {
    return c;
    
    }
    }
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            String username = jLabel2.getText(); 
            String oldPassword = new String(jPasswordField1.getPassword());
            String newPassword = new String(jPasswordField2.getPassword());

            if (oldPassword.isEmpty() || newPassword.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter both old and new passwords");
                return;
            }

            if (oldPassword.equals(newPassword)) {
                JOptionPane.showMessageDialog(this, "New password cannot be the same as old password");
                return;
            }

            String hashedOldPassword = Hash(oldPassword);
            String hashedNewPassword = Hash(newPassword);

            try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/asms_schema", "root", "root..")) {

            try (PreparedStatement ps = con.prepareStatement(
                "SELECT password, useremail FROM userdetails WHERE username = ?")) {
            ps.setString(1, username);

            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(this, "User not found");
                    return;
                }

                String storedPassword = rs.getString("password");
                if (!hashedOldPassword.equals(storedPassword)) {
                    JOptionPane.showMessageDialog(this, "Current password is incorrect");
                    return;
                }

                try (PreparedStatement updatePs = con.prepareStatement(
                    "UPDATE userdetails SET password = ? WHERE username = ?")) {
                updatePs.setString(1, hashedNewPassword);
                updatePs.setString(2, username);

                int updated = updatePs.executeUpdate();
                if (updated > 0) {
                    logPasswordChangeActivity(con, username);

                    String email = rs.getString("useremail");
                    sendPasswordChangeEmail(username, email, newPassword);

                    JOptionPane.showMessageDialog(this, "Password changed successfully");
                    clearPasswordFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Password update failed");
                }
            }
        }
        }
        }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error changing password: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        }

        private void clearPasswordFields() {
            jPasswordField1.setText("");
            jPasswordField2.setText("");
        }

        private void logPasswordChangeActivity(Connection con, String username) throws SQLException {
            try (PreparedStatement ps = con.prepareStatement(
                "INSERT INTO useractivities (username, activitytype, details) VALUES (?, ?, ?)")) {
            ps.setString(1, username);
            ps.setString(2, "Password Change");
            ps.setString(3, "User changed their own password");
            ps.executeUpdate();
        }
        }

        private void sendPasswordChangeEmail(String username, String receiver, String newPassword) {
            try {
                String subject = "Password Changed Notification";
                String body = "Hello " + username + ",\n\n" +
                "Your password was successfully changed: \n\n" +
                newPassword +
                " If you didn't make this change, please contact IT immediately.\n\n" +
                "Best Regards,\n" +
                "The ASMS Team";

                EmailSender.send(receiver, subject, body);
            } catch (Exception e) {
                System.err.println("Failed to send email: " + e.getMessage());
            }

            // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void getProfile() {


    String query = """
        SELECT 
            name, dob, phone, useremail, gender, unit, role
        FROM userdetails where username=?
        ORDER BY user_id ASC
        """;

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setString(1, login.jTextField1.getText());
        ResultSet rs = pst.executeQuery(); 

        while (rs.next()) {
                jLabel10.setText(rs.getString("name"));
                jLabel11.setText(rs.getDate("dob").toString());
                jLabel12.setText(rs.getString("phone"));
                jLabel13.setText(rs.getString("useremail"));
                jLabel14.setText(rs.getString("gender"));
                jLabel15.setText(rs.getString("unit"));
                jLabel16.setText(rs.getString("role"));
            
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
public void displayShift(JTable shiftsTable) {
    String username = jLabel2.getText();

    try {
  
        Class.forName("com.mysql.cj.jdbc.Driver");
        String staffname = null;
        try (
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
            PreparedStatement ps = con.prepareStatement("SELECT name FROM userdetails WHERE username = ?");
        ) {
            ps.setString(1, username);
            ResultSet rb = ps.executeQuery();

            if (rb.next()) {
                staffname = rb.getString("name");
            } else {
                JOptionPane.showMessageDialog(this, "No user found with username: " + username);
                return;
            }
        }

        String query = """
            SELECT 
                s.id,
                s.staff_name,
                s.shift_date,
                s.shift_start_time,
                s.shift_end_time,
                d.unit
            FROM shifts s
            JOIN userdetails d ON s.staff_name = d.name
            WHERE d.name = ?
        """;

        try (
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
            PreparedStatement pst = conn.prepareStatement(query);
        ) {
            pst.setString(1, staffname);
            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) shiftsTable.getModel();
            model.setRowCount(0);
            String[] columnNames = {"Shift ID", "Staff Name", "Shift Date", "Shift Time", "Staff Unit"};
            model.setColumnIdentifiers(columnNames);

            while (rs.next()) {
                String startTime = rs.getTime("shift_start_time").toString().substring(0, 5);
                String endTime = rs.getTime("shift_end_time").toString().substring(0, 5);
                String shiftTime = startTime + "-" + endTime;

                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("staff_name"),
                    rs.getDate("shift_date"),
                    shiftTime,
                    rs.getString("unit")
                });
            }

        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nonSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nonSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nonSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nonSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    try {
        UIManager.setLookAndFeel(new FlatLightLaf());
    } catch (UnsupportedLookAndFeelException e) {
        e.printStackTrace();
    }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nonSupervisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
