/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pauasms;

import classes.ActivityUpdater;
import classes.EmailSender;
import classes.Messenger;
import com.formdev.flatlaf.FlatLightLaf;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.sql.Timestamp;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author Nkon1
 */
public class supervisor extends javax.swing.JFrame {

    /**
     * Creates new form supervisor
     */
    public supervisor() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/logo3.png"));
        setIconImage(icon.getImage());
        
        //Setting Frame Title
        this.setTitle("Supervising Staff");
        
        try{
            jLabel2.setText(login.jTextField1.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error getting username. Please Log In. Error: " + e.getMessage());
            System.out.println("Error getting username. Please Log In. Error: " + e.getMessage());
        }
        
        String supName = jLabel2.getText();
//        String supUnit = null;

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
         PreparedStatement ps = conn.prepareStatement("SELECT unit FROM userdetails WHERE username = ?")) {

        ps.setString(1, supName);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            Globals.supUnit = rs.getString("unit");
        } else {
            JOptionPane.showMessageDialog(this, "Could not determine supervisor's unit.");
            return; // Stop if unit not found
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
        
        
        ActivityUpdater sup = new ActivityUpdater();
        
        ScheduledExecutorService scheduler4 = Executors.newSingleThreadScheduledExecutor();
        scheduler4.scheduleAtFixedRate(() -> {
            SwingUtilities.invokeLater(() -> {
            manageSupUsers(jTable1); 
            });
        }, 0, 2500, TimeUnit.MILLISECONDS);
        
        
        ScheduledExecutorService scheduler5 = Executors.newSingleThreadScheduledExecutor();
        scheduler5.scheduleAtFixedRate(() -> {
            SwingUtilities.invokeLater(() -> {
            sup.viewShifts(jTable2, jLabel2.getText()); 
            });
        }, 0, 2500, TimeUnit.MILLISECONDS);
        
        ScheduledExecutorService scheduler6 = Executors.newSingleThreadScheduledExecutor();
        scheduler6.scheduleAtFixedRate(() -> {
            SwingUtilities.invokeLater(() -> {
            sup.viewSwapRequests(jTable3, jLabel2.getText()); 
            });
        }, 0, 30000, TimeUnit.MILLISECONDS);  
        
        ScheduledExecutorService scheduler7 = Executors.newSingleThreadScheduledExecutor();
        scheduler7.scheduleAtFixedRate(() -> {
            SwingUtilities.invokeLater(() -> {
            manageSupAttendance(jTable4);
            });
        }, 0, 2500, TimeUnit.MILLISECONDS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(46, 56, 106));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Welcome:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("_________");

        jTabbedPane1.setBackground(new java.awt.Color(153, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(46, 56, 106));

        jPanel2.setBackground(new java.awt.Color(46, 56, 106));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Users", jPanel2);

        jPanel3.setBackground(new java.awt.Color(46, 56, 106));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setBackground(new java.awt.Color(46, 56, 106));
        jButton1.setText("Upload Shifts to Database");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(46, 56, 106));
        jButton2.setText("Download Shifts from Database");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(46, 56, 106));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Filter By:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Date:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Staff ID:");

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(102, 0, 0));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(46, 56, 106));
        jButton8.setText("Filter");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane6)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Shifts", jPanel3);

        jPanel4.setBackground(new java.awt.Color(46, 56, 106));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton4.setBackground(new java.awt.Color(46, 56, 106));
        jButton4.setText("Approve");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(46, 56, 106));
        jButton5.setText("Deny");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(695, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(0, 305, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Swap Requests", jPanel4);

        jPanel5.setBackground(new java.awt.Color(46, 56, 106));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Filter By:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Date: ");

        jDateChooser1.setBackground(new java.awt.Color(204, 204, 204));
        jDateChooser1.setForeground(new java.awt.Color(102, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Staff ID:");

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(102, 0, 0));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jButton6.setBackground(new java.awt.Color(46, 56, 106));
        jButton6.setText("Filter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(46, 56, 106));
        jButton7.setText("Filter");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(46, 56, 106));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Generate ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(46, 56, 106));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily", "Weekly", "Monthly" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Generate Report:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(112, 112, 112)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(136, 136, 136))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6)
                        .addComponent(jButton7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Attendance Logs", jPanel5);

        jPanel6.setBackground(new java.awt.Color(46, 56, 106));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Old Password:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("New Password:");

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setForeground(new java.awt.Color(102, 0, 0));

        jPasswordField2.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setForeground(new java.awt.Color(102, 0, 0));

        jButton10.setBackground(new java.awt.Color(46, 56, 106));
        jButton10.setText("Reset Password");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButton10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPasswordField2))))
                .addGap(495, 495, 495))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton10)
                .addContainerGap(466, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reset Password", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(77, 77, 77))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public class Globals {
    public static String supUnit = null;
}
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int result = jFileChooser1.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = jFileChooser1.getSelectedFile();
        String filePath = selectedFile.getAbsolutePath();

        String insertSQL = "INSERT INTO shifts (staff_name, shift_date, shift_start_time, shift_end_time, unit) VALUES (?, ?, ?, ?, ?)";

        try (
            Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
            BufferedReader br = new BufferedReader(new FileReader(filePath));
            PreparedStatement pstmt = conn.prepareStatement(insertSQL);
        ) {
            br.readLine(); // Skip header line

            String line;
            while ((line = br.readLine()) != null) {
                String[] values = line.split(",");

                if (values.length < 5) continue; // Skip incomplete lines

                String staffName = values[0].trim();  
                String dateStr = values[1].trim();
                String startTimeStr = values[2].trim();
                String endTimeStr = values[3].trim();
                String unit = values[4].trim();

                java.util.Date utilDate = new SimpleDateFormat("yyyy-MM-dd").parse(dateStr);
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

                // Parse times
                java.sql.Time shiftStartTime = java.sql.Time.valueOf(startTimeStr + ":00");
                java.sql.Time shiftEndTime = java.sql.Time.valueOf(endTimeStr + ":00");

                pstmt.setString(1, staffName);
                pstmt.setDate(2, sqlDate);
                pstmt.setTime(3, shiftStartTime);
                pstmt.setTime(4, shiftEndTime);
                pstmt.setString(5, unit);
                pstmt.addBatch();
            }

            pstmt.executeBatch();
            JOptionPane.showMessageDialog(this, "Shift roster uploaded successfully!");

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error uploading shift roster: " + ex.getMessage());
        }

        Messenger shiftsender = new Messenger();
        shiftsender.shiftsMail();
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ActivityUpdater.exportRosterToCSV(jFileChooser1, this);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String username = jLabel2.getText();

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/asms_schema", "root", "root..");

            PreparedStatement ps = con.prepareStatement("SELECT unit FROM userdetails WHERE username = ?");
            ps.setString(1, username);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String unit = rs.getString("unit");

                PreparedStatement pstmt = con.prepareStatement("DELETE FROM shifts WHERE unit = ?");
                pstmt.setString(1, unit);

                int rowsDeleted = pstmt.executeUpdate(); // ✅ This actually performs the deletion

                JOptionPane.showMessageDialog(this, "Roster cleared for unit: " + unit + ". Rows deleted: " + rowsDeleted);
            } else {
                JOptionPane.showMessageDialog(this, "User unit not found.");
            }

            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int selectedRow = jTable3.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a swap request to approve.");
            return;
        }

        int swapId = (int) jTable3.getValueAt(selectedRow, 0);

        try (Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/asms_schema", "root", "root..")) {

            PreparedStatement getSwap = conn.prepareStatement(
                    "SELECT requester_shift_id, target_shift_id FROM shift_swaps WHERE id = ?");
            getSwap.setInt(1, swapId);
            ResultSet rs = getSwap.executeQuery();

            if (rs.next()) {
                int requesterShiftId = rs.getInt("requester_shift_id");
                int targetShiftId = rs.getInt("target_shift_id");

                PreparedStatement getShifts = conn.prepareStatement(
                        "SELECT id, staff_name FROM shifts WHERE id IN (?, ?)");
                getShifts.setInt(1, requesterShiftId);
                getShifts.setInt(2, targetShiftId);
                ResultSet shiftSet = getShifts.executeQuery();

                String requesterName = "", targetName = "";

                while (shiftSet.next()) {
                    int shiftId = shiftSet.getInt("id");
                    String name = shiftSet.getString("staff_name");
                    if (shiftId == requesterShiftId) {
                        requesterName = name;
                    } else if (shiftId == targetShiftId) {
                        targetName = name;
                    }
                }

                PreparedStatement updateShifts = conn.prepareStatement(
                        "UPDATE shifts SET staff_name = ? WHERE id = ?");
                updateShifts.setString(1, targetName);
                updateShifts.setInt(2, requesterShiftId);
                updateShifts.addBatch();

                updateShifts.setString(1, requesterName);
                updateShifts.setInt(2, targetShiftId);
                updateShifts.addBatch();

                updateShifts.executeBatch();

                PreparedStatement approveSwap = conn.prepareStatement(
                        "UPDATE shift_swaps SET status = 'Approved' WHERE id = ?");
                approveSwap.setInt(1, swapId);
                approveSwap.executeUpdate();

                JOptionPane.showMessageDialog(this, "Shift swap approved and shifts updated.");
                
                ActivityUpdater one = new ActivityUpdater();
                
                one.viewSwapRequests(jTable3, jLabel2.getText());
                
                Messenger two = new  Messenger();
                two.sendSwapApprovedMail(swapId);

            } else {
                JOptionPane.showMessageDialog(this, "Swap request not found.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error approving swap: " + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int selectedRow = jTable3.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a swap request to deny.");
            return;
        }

        int swapId = (int) jTable3.getValueAt(selectedRow, 0);

        try (Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
             PreparedStatement pst = conn.prepareStatement(
                     "UPDATE shift_swaps SET status = 'Declined' WHERE id = ?")) {

            pst.setInt(1, swapId);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Swap request denied.");
            
            ActivityUpdater one = new ActivityUpdater();
            one.viewSwapRequests(jTable3, jLabel2.getText());
            
            Messenger two = new  Messenger();
            two.sendSwapDeniedMail(swapId);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error denying swap: " + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    String username = jLabel2.getText();
    Date selectedDate = jDateChooser1.getDate();
    String staffId = jTextField1.getText().trim();
    
    if (selectedDate == null) {
        JOptionPane.showMessageDialog(this, "Please select a date first", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/asms_schema", 
            "root", 
            "root..")) {
        
        String unit;
        try (PreparedStatement ps = con.prepareStatement(
                "SELECT unit FROM userdetails WHERE username = ?")) {
            ps.setString(1, username);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(this, "Supervisor not found", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                unit = rs.getString("unit");
            }
        }

        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        model.setRowCount(0);
        
        if (model.getColumnCount() == 0) {
            model.setColumnIdentifiers(new String[]{
                "User ID", "Name", "Sign in Time", 
                "Sign out Time", "Sign in Status", "Sign out Status"
            });
        }

        StringBuilder queryBuilder = new StringBuilder("""
            SELECT sl.*, ud.user_id 
            FROM signin_log sl
            JOIN userdetails ud ON sl.name = ud.name
            WHERE ud.unit = ? 
            AND DATE(sl.sign_in_time) = ?
            """);
        
        if (!staffId.isEmpty()) {
            queryBuilder.append(" AND ud.user_id = ?");
        }
        queryBuilder.append(" ORDER BY sl.sign_in_time DESC");

        try (PreparedStatement psa = con.prepareStatement(queryBuilder.toString())) {
            psa.setString(1, unit);
            psa.setDate(2, new java.sql.Date(selectedDate.getTime()));
            
            if (!staffId.isEmpty()) {
                psa.setInt(3, Integer.parseInt(staffId));
            }
            
            try (ResultSet rs1 = psa.executeQuery()) {
                while (rs1.next()) {
                    model.addRow(new Object[]{
                        rs1.getInt("user_id"),
                        rs1.getString("name"),
                        formatDateTime(rs1.getTimestamp("sign_in_time")),
                        formatDateTime(rs1.getTimestamp("sign_out_time")),
                        rs1.getString("sign_in_status"),
                        rs1.getString("sign_out_status")
                    });
                }
                
                if (model.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, 
                        "No records found for the selected filters", 
                        "Information", 
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Invalid Staff ID format. Please enter a numeric value.", 
            "Input Error", 
            JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Database error: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Unexpected error: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    
        // TODO add your handling code here:
}

private String formatDateTime(Timestamp timestamp) {
    if (timestamp == null) return "N/A";
    return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(timestamp);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    String userIdText = jTextField1.getText().trim(); 
    
    if (userIdText.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Please enter a User ID", 
            "Input Required", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int userId = Integer.parseInt(userIdText);
        
        try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/asms_schema", 
                "root", 
                "root..")) {
            
            DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
            model.setRowCount(0);
            
            if (model.getColumnCount() == 0) {
                model.setColumnIdentifiers(new String[]{
                    "User ID", "Name", "Sign in Time", 
                    "Sign out Time", "Sign in Status", "Sign out Status"
                });
            }

            String query = """
                SELECT sl.*, ud.user_id 
                FROM signin_log sl
                JOIN userdetails ud ON sl.name = ud.name
                WHERE ud.user_id = ?
                ORDER BY sl.sign_in_time DESC
                """;
                
            try (PreparedStatement psa = con.prepareStatement(query)) {
                psa.setInt(1, userId);
                
                try (ResultSet rs = psa.executeQuery()) {
                    boolean hasResults = false;
                    
                    while (rs.next()) {
                        hasResults = true;
                        model.addRow(new Object[]{
                            rs.getInt("user_id"),
                            rs.getString("name"),
                            formatDateTime(rs.getTimestamp("sign_in_time")),
                            formatDateTime(rs.getTimestamp("sign_out_time")),
                            rs.getString("sign_in_status"),
                            rs.getString("sign_out_status")
                        });
                    }
                    
                    if (!hasResults) {
                        JOptionPane.showMessageDialog(this, 
                            "No records found for User ID: " + userId, 
                            "No Results", 
                            JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Invalid User ID format. Please enter a numeric value.", 
            "Input Error", 
            JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Database error: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Unexpected error: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String username = jLabel2.getText(); 
        Date selectedDate = jDateChooser2.getDate();
        String staffIdText = jTextField2.getText().trim();

        if (selectedDate == null && staffIdText.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please select a date or enter a Staff ID", 
                "Filter Required", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String unit = null;

        try (Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/asms_schema", 
                "root", 
                "root..");
             PreparedStatement ps = conn.prepareStatement(
                "SELECT unit FROM userdetails WHERE username = ?")) {

            ps.setString(1, username);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                unit = rs.getString("unit");
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Unit not found for supervisor", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Error fetching unit: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable6.getModel();
        model.setRowCount(0);

        model.setColumnIdentifiers(new String[]{
            "Shift ID", "Staff Name", "Shift Date", "Shift Time", "Staff Unit"
        });

        StringBuilder queryBuilder = new StringBuilder("""
            SELECT s.id, s.staff_name, s.shift_date, 
                   s.shift_start_time, s.shift_end_time, s.unit,
                   ud.user_id
            FROM shifts s
            JOIN userdetails ud ON s.staff_name = ud.name
            WHERE s.unit = ?
            """);

        if (selectedDate != null) {
            queryBuilder.append(" AND s.shift_date = ?");
        }

        if (!staffIdText.isEmpty()) {
            queryBuilder.append(" AND ud.user_id = ?");
        }

        queryBuilder.append(" ORDER BY s.shift_date, s.shift_start_time");

        try (Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/asms_schema", 
                "root", 
                "root..");
             PreparedStatement pst = conn.prepareStatement(queryBuilder.toString())) {

            int paramIndex = 1;
            pst.setString(paramIndex++, unit);

            if (selectedDate != null) {
                pst.setDate(paramIndex++, new java.sql.Date(selectedDate.getTime()));
            }

            if (!staffIdText.isEmpty()) {
                try {
                    int staffId = Integer.parseInt(staffIdText);
                    pst.setInt(paramIndex, staffId);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, 
                        "Invalid Staff ID format", 
                        "Input Error", 
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            ResultSet rs = pst.executeQuery();
            boolean hasResults = false;

            while (rs.next()) {
                hasResults = true;
                String startTime = rs.getTime("shift_start_time").toString().substring(0, 5);
                String endTime = rs.getTime("shift_end_time").toString().substring(0, 5);
                String shiftTime = startTime + " - " + endTime;

                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("staff_name"),
                    rs.getDate("shift_date"),
                    shiftTime,
                    rs.getString("unit")
                });
            }

            if (!hasResults) {
                JOptionPane.showMessageDialog(this, 
                    "No shifts found matching the filters", 
                    "Information", 
                    JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Database error: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String username = jLabel2.getText();

        String unit = null;
        try (Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
             PreparedStatement pst = conn.prepareStatement(
                "SELECT unit FROM userdetails WHERE username = ?")) {

            pst.setString(1, username);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                unit = rs.getString("unit");
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Could not determine your unit", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String reportType = jComboBox1.getSelectedItem().toString();

        // Let user choose save location
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save " + reportType + " Report for " + unit);
        fileChooser.setSelectedFile(new File(unit + "_" + reportType.toLowerCase() + "_report.csv"));

        if (fileChooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        String filePath = fileChooser.getSelectedFile().getAbsolutePath();
        if (!filePath.toLowerCase().endsWith(".csv")) {
            filePath += ".csv";
        }

        try (Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
             BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {


            String query = "SELECT ud.name, ud.user_id, " +
                          "DATE(sl.sign_in_time) as date, " +
                          "TIME(sl.sign_in_time) as sign_in_time, " +
                          "TIME(sl.sign_out_time) as sign_out_time, " +
                          "sl.sign_in_status, sl.sign_out_status " +
                          "FROM signin_log sl " +
                          "JOIN userdetails ud ON sl.name = ud.name " +
                          "WHERE ud.unit = ? ";
            switch (reportType) {
                case "Daily":
                    query += "AND DATE(sl.sign_in_time) = CURDATE() ";
                    break;
                case "Weekly":
                    query += "AND YEARWEEK(sl.sign_in_time, 1) = YEARWEEK(CURDATE(), 1) ";
                    break;
                case "Monthly":
                    query += "AND YEAR(sl.sign_in_time) = YEAR(CURDATE()) " +
                             "AND MONTH(sl.sign_in_time) = MONTH(CURDATE()) ";
                    break;
            }
            query += "ORDER BY date, ud.name";

            try (PreparedStatement pst = conn.prepareStatement(query)) {
                pst.setString(1, unit);
                ResultSet rs = pst.executeQuery();

                // Write CSV header
                writer.write("Staff Name,Staff ID,Date,Sign In Time,Sign Out Time,Sign In Status,Sign Out Status");
                writer.newLine();

                SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");

                while (rs.next()) {
                    writer.write(String.format("\"%s\",%d,%s,%s,%s,\"%s\",\"%s\"",
                        rs.getString("name"),
                        rs.getInt("user_id"),
                        rs.getDate("date"),
                        rs.getTime("sign_in_time") != null ? 
                            timeFormat.format(rs.getTime("sign_in_time")) : "N/A",
                        rs.getTime("sign_out_time") != null ? 
                            timeFormat.format(rs.getTime("sign_out_time")) : "N/A",
                        rs.getString("sign_in_status"),
                        rs.getString("sign_out_status")
                    ));
                    writer.newLine();
                }
            }

            JOptionPane.showMessageDialog(this,
                reportType + " report for " + unit + " generated successfully!\n" +
                "Saved to: " + filePath,
                "Report Generated",
                JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error generating report: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    public String Hash(String c)
    {
    try{
    MessageDigest msgDigest = MessageDigest.getInstance("MD5");
     msgDigest.update((new String(c)).getBytes("UTF8"));
     String passHash = new String(msgDigest.digest());
     return passHash;
     
     
    }
    
    catch (Exception ex)
    {
    return c;
    
    }
    }
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
try {
        String username = jLabel2.getText(); 
        String oldPassword = new String(jPasswordField1.getPassword());
        String newPassword = new String(jPasswordField2.getPassword());
        
        if (oldPassword.isEmpty() || newPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both old and new passwords");
            return;
        }
        
        if (oldPassword.equals(newPassword)) {
            JOptionPane.showMessageDialog(this, "New password cannot be the same as old password");
            return;
        }
        
        String hashedOldPassword = Hash(oldPassword);
        String hashedNewPassword = Hash(newPassword);
        
        try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/asms_schema", "root", "root..")) {
            
            try (PreparedStatement ps = con.prepareStatement(
                    "SELECT password, useremail FROM userdetails WHERE username = ?")) {
                ps.setString(1, username);
                
                try (ResultSet rs = ps.executeQuery()) {
                    if (!rs.next()) {
                        JOptionPane.showMessageDialog(this, "User not found");
                        return;
                    }
                    
                    String storedPassword = rs.getString("password");
                    if (!hashedOldPassword.equals(storedPassword)) {
                        JOptionPane.showMessageDialog(this, "Current password is incorrect");
                        return;
                    }
                    
                    try (PreparedStatement updatePs = con.prepareStatement(
                            "UPDATE userdetails SET password = ? WHERE username = ?")) {
                        updatePs.setString(1, hashedNewPassword);
                        updatePs.setString(2, username);
                        
                        int updated = updatePs.executeUpdate();
                        if (updated > 0) {
                            logPasswordChangeActivity(con, username);
                            
                            String email = rs.getString("useremail");
                            sendPasswordChangeEmail(username, email, newPassword);
                            
                            JOptionPane.showMessageDialog(this, "Password changed successfully");
                            clearPasswordFields();
                        } else {
                            JOptionPane.showMessageDialog(this, "Password update failed");
                        }
                    }
                }
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Error changing password: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}
   
    private void clearPasswordFields() {
    jPasswordField1.setText("");
    jPasswordField2.setText("");
}

private void logPasswordChangeActivity(Connection con, String username) throws SQLException {
    try (PreparedStatement ps = con.prepareStatement(
            "INSERT INTO useractivities (username, activitytype, details) VALUES (?, ?, ?)")) {
        ps.setString(1, username);
        ps.setString(2, "Password Change");
        ps.setString(3, "User changed their own password");
        ps.executeUpdate();
    }
}

private void sendPasswordChangeEmail(String username, String receiver, String newPassword) {
    try {
        String subject = "Password Changed Notification";
        String body = "Hello " + username + ",\n\n" +
                     "Your password was successfully changed.\n\n" +
                     "For security reasons, we don't include your new password in this email.\n\n" +
                     "If you didn't make this change, please contact IT immediately.\n\n" +
                     "Best Regards,\n" +
                     "The ASMS Team";
        
        EmailSender.send(receiver, subject, body);
    } catch (Exception e) {
        System.err.println("Failed to send email: " + e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void manageSupUsers(JTable populerItemsTable) {
        String username = jLabel2.getText();
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
        System.out.println("connected");

        PreparedStatement ps= con.prepareStatement("select unit from userdetails where username=?");
        ps.setString(1, username);
        ResultSet rs=ps.executeQuery();
        
        if(rs.next()){
            String unit = rs.getString("unit");
            DefaultTableModel model = (DefaultTableModel) populerItemsTable.getModel();
            model.setRowCount(0);

            String[] columnNames = {"User ID", "Name", "Phone", "Email", "Unit", "Role", "Log in Time"};
            model.setColumnIdentifiers(columnNames);

            String query = """
                SELECT 
                    user_id, name, phone, useremail, unit, role, logintime
                FROM userdetails WHERE unit = ?
                ORDER BY user_id ASC
                """;
            
            try {
                
            PreparedStatement psa = con.prepareStatement(query);
            psa.setString(1, unit);
            ResultSet rs1 = psa.executeQuery();
//            ResultSet rt =psa.executeQuery();

            while (rs1.next()) {
                model.addRow(new Object[]{
                    rs1.getInt("user_id"),
                    rs1.getString("name"),
                    rs1.getString("phone"),
                    rs1.getString("useremail"),
                    rs1.getString("unit"),
                    rs1.getString("role"),
                    rs1.getString("logintime")
                });
            }

       } catch (Exception e) {
           e.printStackTrace();
       }

        }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
}
    
    public void manageSupAttendance(JTable populerItemsTable) {
        String username = jLabel2.getText();
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/asms_schema", "root", "root..");
        System.out.println("connected");

        PreparedStatement ps= con.prepareStatement("select unit from userdetails where username=?");
        ps.setString(1, username);
        ResultSet rs=ps.executeQuery();
        
        if(rs.next()){
            String unit = rs.getString("unit");
            DefaultTableModel model = (DefaultTableModel) populerItemsTable.getModel();
            model.setRowCount(0);

            String[] columnNames = {"User ID", "Name", "Sign in Time", "Sign out Time", "Sign in Status", "Sign out Status"};
            model.setColumnIdentifiers(columnNames);

            String query = """
                SELECT sl.*, ud.user_id 
                FROM signin_log sl
                JOIN userdetails ud ON sl.name = ud.name
                WHERE ud.unit = ?
                ORDER BY sl.sign_in_time DESC;
                """;
            
            try {
                
            PreparedStatement psa = con.prepareStatement(query);
            psa.setString(1, unit);
            ResultSet rs1 = psa.executeQuery();
//            ResultSet rt =psa.executeQuery();

            while (rs1.next()) {
                model.addRow(new Object[]{
                    rs1.getInt("user_id"),
                    rs1.getString("name"),
                    rs1.getString("sign_in_time"),
                    rs1.getString("sign_out_time"),
                    rs1.getString("sign_in_status"),
                    rs1.getString("sign_out_status"),
                });
            }

       } catch (Exception e) {
           e.printStackTrace();
       }

        }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    try {
        UIManager.setLookAndFeel(new FlatLightLaf());
    } catch (UnsupportedLookAndFeelException e) {
        e.printStackTrace();
    }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supervisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
